version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Echo install 

  pre_build:
    commands:
      - echo Pre Build
      - npm install     

  build:
    commands:
      - echo build phase
      - npm run build

  post_build:
    commands:
      - echo post build
      - aws s3 sync ./dist/softrams-racing s3://angularfinal
    